name: ssa
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2023.01.10=h06a4308_0
  - certifi=2022.12.7=py38h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=1.1.1t=h7f8727e_0
  - pip=23.0.1=py38h06a4308_0
  - python=3.8.16=h7a1cb2a_3
  - readline=8.2=h5eee18b_0
  - setuptools=65.6.3=py38h06a4308_0
  - sqlite=3.41.1=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.38.4=py38h06a4308_0
  - xz=5.2.10=h5eee18b_1
  - zlib=1.2.13=h5eee18b_0
  - pip:
    - https://download.pytorch.org/whl/cu111/torch-1.9.1%2Bcu111-cp38-cp38-linux_x86_64.whl
    - https://download.pytorch.org/whl/cu111/torchvision-0.10.1%2Bcu111-cp38-cp38-linux_x86_64.whl
    - https://download.pytorch.org/whl/torchaudio-0.9.1-cp38-cp38-linux_x86_64.whl
    - addict==2.4.0
    - blis==0.7.9
    - catalogue==2.0.8
    - charset-normalizer==3.1.0
    - click==8.1.3
    - confection==0.0.4
    - contourpy==1.0.7
    - cycler==0.11.0
    - cymem==2.0.7
    - filelock==3.11.0
    - fonttools==4.39.3
    - huggingface-hub==0.13.4
    - idna==3.4
    - importlib-resources==5.12.0
    - jinja2==3.1.2
    - kiwisolver==1.4.4
    - langcodes==3.3.0
    - markupsafe==2.1.2
    - matplotlib==3.7.1
    - https://download.openmmlab.com/mmcv/dist/cu111/torch1.9.0/mmcv_full-1.3.18-cp38-cp38-manylinux1_x86_64.whl
    - mmdet==2.25.3
    - murmurhash==1.0.9
    - numpy==1.24.2
    - opencv-python==4.7.0.72
    - packaging==23.0
    - pathy==0.10.1
    - pillow==9.5.0
    - preshed==3.0.8
    - pycocotools==2.0.6
    - pydantic==1.10.7
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pyyaml==6.0
    - regex==2023.3.23
    - requests==2.28.2
    - scipy==1.10.1
    - six==1.16.0
    - smart-open==6.3.0
    - spacy==3.5.1
    - spacy-legacy==3.0.12
    - spacy-loggers==1.0.4
    - srsly==2.4.6
    - terminaltables==3.1.10
    - thinc==8.1.9
    - tokenizers==0.13.3
    - tqdm==4.65.0
    - transformers==4.27.4
    - typer==0.7.0
    - typing-extensions==4.5.0
    - urllib3==1.26.15
    - wasabi==1.1.1
    - yapf==0.32.0
    - zipp==3.15.0
    - mmsegmentation==0.26.0
